Portal example
kibalabs/ui-react pull request #65
Opened 2021-04-01 18:26 UTC by MoiyadKayda

## Description
I have changed the background so it is easy to test the component. And want some suggestions on the placement. I have tried to make it the same as other libraries have. And the width of the portal is 0 by default, is it correct.

## Screenshots:
![image](https://user-images.githubusercontent.com/42097538/113337768-daee2a00-9345-11eb-8a70-81b96a6b4f54.png)

## Checklist:

- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] I have updated the documentation accordingly

2021-04-03 17:54 UTC, MoiyadKayda commented on src/particles/portal/component.tsx
> +export function getOffsetTop(rect: any, vertical: number | string): number {
Please change the type of the `rect` argument.

2021-04-03 17:57 UTC, MoiyadKayda commented on src/particles/portal/component.tsx
> +export function getOffsetTop(rect: any, vertical: number | string): number {
I was not able to get the type of this arg. The value of this arg is going to be of `anchorElementNodeRect = props.anchorElement?.current?.getBoundingClientRect();`

2021-04-03 17:57 UTC, MoiyadKayda commented on src/particles/portal/component.tsx
> +export function getOffsetLeft(rect: any, horizontal: number | string) {
Same here

2021-04-14 07:57 UTC, krishan711 approved these changes

2021-04-14 07:58 UTC, krishan711 commented on src/molecules/list/component.tsx
>  export const List = (props: IListProps): React.ReactElement => {
Please update changelog

2021-04-14 07:58 UTC, krishan711 requested changes
pls update changelog

2021-04-14 11:46 UTC, krishan711 approved these changes

2021-04-14 11:46 UTC, merged